### ISSUE TITLE
Configure semantic tags for species

### ISSUE THREAD

**Issue by dosumis** [EBISPOT/cap-pipeline-config#1]
Aim: Add a set of semantic tags to NCBI taxonomy terms that can be used to filter and boost terms in the CAP platform dataset metadata species field autocomplete:
* Tag all species terms with a Species tag (for filter).  NCBI taxonomy flags species using an annotation property axiom [has_rank](http://purl.obolibrary.org/obo/ncbitaxon#has_rank) [species](http://purl.obolibrary.org/obo/NCBITaxon_species), so this tag must be added via a SPARQL query. 
* Tag all [Metazoa]((http://purl.obolibrary.org/obo/NCBITaxon_33208) with a Metazoan tag (for use in filter).  This tag should be specified as a class expression (YAML config)
* Tag a manually selected list of terms with Common_species tag (for use in boost).  This should be added via SPARQL:
  * Homo sapiens
  * Mus musculus (mouse)
  * Danio rerio (zebrafish)
  * Drosophila melanogaster (fruit fly)
  * Rattus norvegicus domestica (rat)
  * C. elegans
  * Gallus domesticus (chicken)
  * Ambystoma mexicanum (axolotl) 

TBD: include subspecies?

Source ontology: 
 - It is sufficient to use http://purl.obolibrary.org/obo/ncbitaxon/subsets/taxslim.owl .  This is much smaller than the full NCBI_Taxonomy.  It approximates a list of all species for which published genomes exist + any additional taxa for which we have GO annotation or which are used to define classes in OBO ontologies. 

Species terms are identified by an annotation axiom
has rank http://purl.obolibrary.org/obo/NCBITaxon_species

- [ ] Add semantic tag for Metazoa to https://github.com/EBISPOT/cap-pipeline-config/blob/main/config/prod/neo4j2owl-config.yaml#L16
- [ ] Add SPARQL query to add semantic tag Species here: https://github.com/EBISPOT/cap-pipeline-config/tree/main/config/dumps/sparql (note - we should also clear out irrelevant VFB content here)
- [ ] Add SPARQL query for Common_species  here: https://github.com/EBISPOT/cap-pipeline-config/tree/main/config/dumps/sparql 
- [ ] Add relevant tags from SPARQL queries to SOLR load  https://github.com/VirtualFlyBrain/vfb-pipeline-dumps/blob/master/dumps.Makefile#L67

CC @bvarner-ebi

**Comment by bvarner-ebi** [comment]
IRIs for common species list:

<http://purl.obolibrary.org/obo/NCBITaxon_9606> # Homo sapiens,
<http://purl.obolibrary.org/obo/NCBITaxon_10090> # Mus musculus (mouse),
<http://purl.obolibrary.org/obo/NCBITaxon_7955> # Danio rerio (zebrafish),
<http://purl.obolibrary.org/obo/NCBITaxon_7227> # Drosophila melanogaster (fruit fly),
<http://purl.obolibrary.org/obo/NCBITaxon_10116> # Rattus norvegicus (rat),
<http://purl.obolibrary.org/obo/NCBITaxon_6239> # C. elegans (nematode worm),
<http://purl.obolibrary.org/obo/NCBITaxon_9031> # Gallus domesticus (chicken),
<http://purl.obolibrary.org/obo/NCBITaxon_8296> # Ambystoma mexicanum (axolotl)

A SPARQL query that can be used for QC/confirmation:

```
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX obo: <http://purl.obolibrary.org/obo/>

SELECT DISTINCT *
WHERE {
    ?s <http://purl.obolibrary.org/obo/ncbitaxon#has_rank>  <http://purl.obolibrary.org/obo/NCBITaxon_species>. ?s rdfs:label ?label
VALUES ?s
{obo:NCBITaxon_9606 obo:NCBITaxon_10090 obo:NCBITaxon_7955 obo:NCBITaxon_7227 obo:NCBITaxon_10116 obo:NCBITaxon_6239 obo:NCBITaxon_9031 obo:NCBITaxon_8296
}
}
```

**Comment by dosumis** [comment]
1. This is sufficient for config for Metazoan:

```yaml
neo_node_labelling:
  - classes:
      - NCBITaxon_33208
    label: Metazoan
```

The idea is to label taxa, not anatomical entities or cell types that are in some taxon.

We can remove the Kidney tag config for now and revisit when we work on the cell type field.

2. The SPARQL query for common species boost works fine.  Are you OK with turning this into a SPARQL construct & saving to a file as detailed here: https://github.com/EBISPOT/cap-pipeline-config/tree/main/config/dumps ?

3. Any progress on the SPARQL query for Species? 

4. You are correct that this filter is not needed, although it does no harm:

```yaml
filters:
  solr:
    exclusion:
      iri_prefix:
        - http://virtualflybrain.org/reports/VFBc_
      neo4j_node_label:
        - Channel
```

There is a general cleanup job to do to make a cleaner default config free of VFB specific settings.
