### ISSUE TITLE
Add configuration for Sex field

### ISSUE THREAD

**Issue by ghost** [EBISPOT/cap-pipeline-config#42]
Leveraging [PATO](https://www.ebi.ac.uk/ols/ontologies/pato), filter on select terms under PATO:0001894 'phenotypic sex'.

**Comment by bvarner-ebi** [comment]
@evanbiederstedt, in addition to male and female, would you like to filter on any other term under 'phenotypic sex'?

![Screenshot 2022-04-12 at 08 12 48](https://user-images.githubusercontent.com/95643797/162960229-a5c3ee4a-7d48-4b0b-b181-3963253fd045.png)
