### ISSUE TITLE
Extend Disease tag to include PATO 'normal' 

### ISSUE THREAD

**Issue by dosumis** [EBISPOT/cap-pipeline-config#53]
In line with [CellXGene Anndata spec](), we need to allow PATO:normal in the Disease field.  In the absence of this, we get some very bizarre suggestions for mappings for normal:

<img width="623" alt="image" src="https://user-images.githubusercontent.com/112839/174485791-bad0d114-52cf-4a31-aef8-96c31859b326.png">

To achieve this we need to 

(a) Load PATO into the KB (add  https://github.com/pato-ontology/pato/blob/master/pato-base.owl to https://github.com/kharchenkolab/cap-pipeline-config/blob/main/config/collectdata/vfb_fullontologies.txt)
(b) Add the Disease semantic tag to PATO normal, via a SPARQL query @bvarner-ebi

**Comment by ubyndr** [comment]
Are we going to keep this part in the yaml config?
https://github.com/kharchenkolab/cap-pipeline-config/blob/ff287cc2a57187726408ccf937f9978e340780ee/config/prod/neo4j2owl-config.yaml#L218-L220

**Comment by ubyndr** [comment]
'development' branch is kinda default branch for this repository. pato.owl is already added to the vfb_fullontologies.txt, https://github.com/kharchenkolab/cap-pipeline-config/blob/ff287cc2a57187726408ccf937f9978e340780ee/config/collectdata/vfb_fullontologies.txt#L7.
Do you only want to use the base version of the pato?

**Comment by ubyndr** [comment]
```
[Fatal Error] :16:76: Attribute name "crossorigin" associated with an element type "link" must be followed by the ' = ' character.
INVALID ONTOLOGY FILE ERROR Could not load a valid ontology from file: pato-base.owl
For details see: http://robot.obolibrary.org/errors#invalid-ontology-file-error
```
pato-base.owl has some issues, getting this error message in collectdata pipeline. Used pato.owl as I've mentioned in my previous comment. @dosumis

**Comment by ghost** [comment]
@ubyndr, can we close this ticket?

**Comment by ubyndr** [comment]
Yes, I have re-run the pipeline with the Prefix fix and indexes are ok. Just need to upload them to GCP so Denis can update the SOLR indexes on rc1 and prod.
