### ISSUE TITLE
Implement contextual search for stage (EPIC)

### ISSUE THREAD

**Issue by dosumis** [EBISPOT/cap-pipeline-config#65]
For ref - [CellXGene 2.0 schema stage spec ](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/2.0.0/schema.md#development_stage_ontology_term_id).

### TODO

* Load species specific source ontologies (via edits to https://github.com/kharchenkolab/cap-pipeline-config/blob/development/config/collectdata/vfb_fullontologies.txt) 
   * http://purl.obolibrary.org/obo/fbdv.owl 
   * http://purl.obolibrary.org/obo/wbls.owl
   * http://purl.obolibrary.org/obo/mmusdv.owl
   * http://purl.obolibrary.org/obo/zfs.owl
   * http://purl.obolibrary.org/obo/mmusdv.owl
   * http://purl.obolibrary.org/obo/hsapdv.owl
   * http://purl.obolibrary.org/obo/xao.owl
* Set Developmental_stage tag on all appropriate terms.  This should be done in the YAML config so that all subclasses of the appropriate class in each ontology get the tag  e.g. for FBdv: 'developmental stage' [http://purl.obolibrary.org/obo/FBdv_00005259](http://purl.obolibrary.org/obo/FBdv_00005259).  This extends the existing config, which so far only specifies Uberon stage terms.
* Set Species tags (per ontology):
   * SPARQL driven tag matching on URL.  e.g. STARTSWITH('http://purl.obolibrary.org/obo/FBdv') --> semantic tag: Drosophila_melanogaster
* Implement contextual restrictions.  Details TBA in discussion with @ubyndr

**Comment by ghost** [comment]
> * https://www.ebi.ac.uk/ols/ontologies/mmusdv

@dosumis, would the above be added to [vfb_fullontologies.txt](https://github.com/kharchenkolab/cap-pipeline-config/blob/development/config/collectdata/vfb_fullontologies.txt) or is http://purl.obolibrary.org/obo/mmusdv.owl sufficient?

**Comment by dosumis** [comment]
> @dosumis, would the above be added to [vfb_fullontologies.txt](https://github.com/kharchenkolab/cap-pipeline-config/blob/development/config/collectdata/vfb_fullontologies.txt) or is http://purl.obolibrary.org/obo/mmusdv.owl sufficient?

Please use the PURL.  The OLS link above is a pasto (now fixed).

**Comment by ghost** [comment]
@ubyndr, can you confirm if this has been done:

[ ] Implement contextual restrictions. Details TBA in discussion with @ubyndr

If done, can we close the ticket? If not, can the ticket be assigned to you?

**Comment by ubyndr** [comment]
Is this still relevant with [Contextual search on the CAP API ](https://docs.google.com/document/d/1AoiUMsQib4w4jOo24463iOMtDXsmIsc4X1hVtcbTqAc/edit?usp=sharing). I mean I don't think we handle this alone, but we will handle contextual search for all metadata fields with the new API right? @dosumis

**Comment by dosumis** [comment]
@ubyndr will aim to get final implementation of new config system with this functionality in place, in the next sprint.
