### ISSUE TITLE
Design data structure (YAML) for encoding the business logic for contextual search

### ISSUE THREAD

**Issue by dosumis** [EBISPOT/cap-pipeline-config#67]
Problem:   We need to encode how choosing a term in one field has consequences for the semantic tags used in boosting in other fields.  Semantic tags are just strings, so we need mappings from ontology term IRIs (or curies).

Currently we have a very simple YAML file for this. It just has mappings - not business logic.

```yaml
  "UBERON:0002369" : Adrenal_gland
  "UBERON:0001245" : Anus
  "UBERON:0001154" : Vermiform_appendix
  "UBERON:0001637" : Artery
  "UBERON:0018707" :  Bladder_organ
```

**Comment by ubyndr** [comment]
I think this can be closed since we have a new JSON configuration to do the job. Details can be found in https://capdevelopment.atlassian.net/browse/MVP-1986 EPIC.
